---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s8:
      addresses:
      - 192.168.255.1/30
      routes:
      - to: 192.168.0.0/16
        via: 192.168.255.2
    enp0s19:
      addresses:
      - 192.168.50.10/24